# Generated by Django 3.2.4 on 2021-08-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
