# Generated by Django 3.2.4 on 2022-06-05 12:05

from django.db import migrations, models
import main.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mailtemplate_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер дома')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер,квартиры')),
                ('address_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий по адресу')),
                ('name', models.CharField(max_length=100, verbose_name='компания-партнёр')),
                ('amount', main.models.fields.AmountField(decimal_places=2, default=0, max_digits=12, verbose_name='баланс компании-партнёра')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер договора по сайту')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='дата заключения договора по сайту')),
                ('contract_number_ipad', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер договора по iPad')),
                ('contract_date_ipad', models.DateField(blank=True, null=True, verbose_name='дата заключения договора по iPad')),
                ('owner_name', models.CharField(max_length=100, verbose_name='владелец компании')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='электронная почта для контактов')),
                ('report_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='электронная почта для отсылки отчётов')),
                ('code_1c', models.CharField(blank=True, max_length=50, null=True, verbose_name='код компании-партнёра в 1С')),
                ('reported', models.BooleanField(default=False, verbose_name='Отсылать ежемесячные отчеты?')),
                ('division_of_profit', models.PositiveIntegerField(default=50, verbose_name='коэффициент разделения дохода')),
            ],
            options={
                'verbose_name': 'компания-партнёр',
                'verbose_name_plural': 'компании-партнёры',
                'ordering': ['name'],
            },
        ),
    ]
