{% load i18n %} 
{% get_current_language as LANGUAGE_CODE %}
{
                "m_text_riader": "{% trans 'Текстовая версия' %}",
                "m_pdf_riader": "{% trans 'PDF версия' %}",
                "t_payment": "{% trans 'Оплата выпуска' %}",
                "m_cost": "{% trans 'Стоимость покупки' %}",
                "m_on_account": "{% trans 'У вас на счету' %}",
                "m_replanish": "{% trans 'Пополнить счет' %}",
                "m_subscription": "{% trans 'Подписки' %}",
                "m_bookmarks": "{% trans 'Закладки' %}",
                "btn_subscription": "{% trans 'Подписка 8 руб/сутки' %}",
                "m_abonement": "{% trans 'Абонемент' %}",
                "m_collection": "{% trans 'Моя коллекция' %}",
                "m_payments": "{% trans 'Платежи' %}",
                "m_signin": "{% trans 'Вход' %}",
                "m_register": "{% trans 'Регистрация' %}",
                "m_free": "{% trans 'БЕСПЛАТНО' %}",
                "m_popular": "{% trans 'Популярные' %}",
                "m_publications": "{% trans 'издания' %}",
                "m_password": "{% trans 'Пароль' %}",
                "m_enter": "{% trans 'Войти' %}",
                "m_registr": "{% trans 'Зарегистрироваться' %}",
                "m_Loginerror": "{% trans 'Ошибка входа!' %}",
                "m_buy": "{% trans 'купить' %}",
                "m_subscribe": "{% trans 'Подписаться' %}",
                "m_electronicsub": "{% trans 'Электронная подписка' %}",
                "m_more": "{% trans 'еще' %}",
                "m_issues": "{% trans 'выпуски' %}",
                "m_listentoaudio": "{% trans 'Слушать аудио' %}",
                "m_issue": "{% trans 'Выпуск' %}",
                "m_articles": "{% trans 'Статьи' %}",
                "m_issuea": "{% trans 'Выпуска' %}",
                "m_entermail": "{% trans 'Введите ваш e-mail' %}",
                "m_registration_abonement": "{% trans 'Оформление абонемента' %}"

}