# Generated by Django 3.1.7 on 2021-03-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование категории каталога')),
                ('category_type', models.CharField(choices=[('magazine', 'Журнал'), ('paper', 'Газета'), ('book', 'Книга'), ('abonement', 'Абонемент')], default='magazine', max_length=10, verbose_name='тип издания')),
                ('sorting', models.SmallIntegerField(default=0, verbose_name='Сортировка')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование тега')),
                ('show_in_mobile_api', models.BooleanField(default=False, verbose_name='Показывать ли в API для мобильных устройств?')),
                ('sorting', models.SmallIntegerField(default=0, verbose_name='Сортировка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tags', verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etags', to='catalog.category', verbose_name='Категория')),
            ],
        ),
    ]
