# Generated by Django 3.1.7 on 2021-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_new_catalog',
            field=models.BooleanField(default=False, verbose_name='показывать ли в новом каталоге?'),
        ),
    ]
