# Generated by Django 3.1.7 on 2021-05-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_show_in_new_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='show_in_new_catalog',
        ),
    ]
