# Generated by Django 3.1.7 on 2021-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_show_in_new_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название для URL'),
        ),
    ]
