# Generated by Django 3.2.4 on 2021-08-22 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='дата операции')),
                ('operation', models.IntegerField(choices=[(0, 'Покупка на сайте'), (3, 'Восстановление денег на счёте'), (1, 'Начисление на счёт'), (2, 'Вывод денег со счёта'), (4, 'Генерация подарочного кода'), (5, 'Получение подарка по промокоду'), (6, 'Покупка через iPad-приложение'), (7, 'Начисление на счет администратором'), (8, 'Снятие со счета администратором'), (9, 'Снятие остаточной суммы, при покупке с пополнением счета'), (10, 'Возврат средств за покупку'), (11, 'Бонус на счёт за покупку по акции'), (12, 'Покупка товаров "Киоск у дома"')], verbose_name='тип финансовой операции')),
                ('payment_system', models.IntegerField(blank=True, choices=[(1, 'paymaster'), (2, 'payonline'), (3, 'qiwi'), (4, 'handybank'), (6, 'app store'), (6, 'sberbank')], null=True, verbose_name='платёжная система')),
                ('operation_amount', main.models.fields.AmountField(decimal_places=2, max_digits=12, verbose_name='заявленная сумма операции')),
                ('operation_real_payed', main.models.fields.AmountField(decimal_places=2, max_digits=12, verbose_name='реально оплаченная сумма')),
                ('operation_amount_with_discount', main.models.fields.AmountField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='сумма с учетом скидки')),
                ('discount_type', models.PositiveIntegerField(blank=True, choices=[(1, ' Скидка за наш счет.'), (2, 'Пропорциональная скидка.'), (4, 'Бонус на лицевой счет за наш счет.'), (8, 'Бонус на лицевой счет с пропорциональным разделением.')], null=True, verbose_name='Тип скидки')),
                ('approved', models.BooleanField(default=False, verbose_name='транзакция подтверждена')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('itunes_transaction_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='ID транзакции из квитанции App Store')),
                ('additional', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'денежная транзакция',
                'verbose_name_plural': 'денежные транзакции',
                'ordering': ['-datetime'],
            },
        ),
    ]
