# Generated by Django 3.2.7 on 2022-01-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
