# Generated by Django 3.1.7 on 2021-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование категории каталога')),
                ('category_type', models.CharField(choices=[('magazine', 'Журнал'), ('paper', 'Газета'), ('book', 'Книга'), ('abonement', 'Абонемент')], default='magazine', max_length=10, verbose_name='тип издания')),
                ('sorting', models.SmallIntegerField(default=0, verbose_name='Сортировка')),
            ],
        ),
    ]
