# Generated by Django 3.1.7 on 2021-02-25 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='номер выпуска')),
                ('release_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='дата выхода выпуска')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.journal', verbose_name='издание')),
            ],
        ),
        migrations.CreateModel(
            name='IssuePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(verbose_name='номер страницы')),
                ('file_low', models.ImageField(blank=True, null=True, upload_to='low', verbose_name='файл изображения предпросмотра')),
                ('file_middle', models.ImageField(upload_to='medium', verbose_name='файл страницы')),
                ('file_high', models.ImageField(blank=True, null=True, upload_to='high', verbose_name='файл страницы увеличенный')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_set', to='main.issue', verbose_name='печатное издание')),
            ],
        ),
    ]
