# Generated by Django 3.1.7 on 2021-02-24 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210224_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='release_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='дата выхода выпуска'),
        ),
    ]
