# Generated by Django 3.2.4 on 2021-08-19 09:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import main.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0017_journal_is_export_to_air'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название подписки')),
                ('cost', main.models.fields.AmountField(decimal_places=2, max_digits=12, verbose_name='стоимость подписки')),
                ('is_public', models.BooleanField(default=True, verbose_name='отображать ли на сайте?')),
                ('is_show_ipad', models.BooleanField(default=False, verbose_name='отображать ли в iPad?')),
                ('ipad_tier_subscription_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID tier-а подписки в App Store')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('publishing_pay_part', main.models.fields.AmountField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='отчисления издательству, в рублях')),
                ('count', models.PositiveIntegerField(blank=True, null=True, verbose_name='количество номеров в подписке')),
                ('months', models.PositiveIntegerField(blank=True, null=True, verbose_name='число месяцев')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal', verbose_name='издание')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
                'ordering': ['journal__name', 'count'],
            },
        ),
    ]
