# Generated by Django 3.2.4 on 2021-08-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mailtemplate_alias'),
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('count', models.PositiveIntegerField(verbose_name='количество оставшихся номеров по подписке')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='пользователь')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.subscription', verbose_name='подписка')),
            ],
            options={
                'verbose_name': 'подписка пользователя',
                'verbose_name_plural': 'подписки пользователей',
            },
        ),
    ]
