# Generated by Django 3.2.4 on 2021-08-19 10:10

from django.db import migrations, models
import django.db.models.deletion
import main.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_abonement_userabonement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonementDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', main.models.fields.AmountField(decimal_places=2, max_digits=12, verbose_name='Cтоимость подписки')),
                ('prolongation', models.PositiveIntegerField(help_text='выпусков', verbose_name='Действиет при покупке от')),
                ('abonement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.abonement')),
            ],
            options={
                'verbose_name': 'Скидка на Абонемент',
                'verbose_name_plural': 'Скидки на Абонементы',
            },
        ),
    ]
