# Generated by Django 3.1.7 on 2021-03-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='отображать в новом?'),
        ),
    ]
