# Generated by Django 3.1.7 on 2021-03-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20210324_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cover_url_mask',
            field=models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='маска url обложки'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_covers_created',
            field=models.BooleanField(default=False, verbose_name='были ли отконвертированы обложки'),
        ),
    ]
