# Generated by Django 3.1.7 on 2021-03-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20210325_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='name_slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название для URL'),
        ),
    ]
