# Generated by Django 3.1.7 on 2021-03-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_journal_cover_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='цена'),
        ),
    ]
