# Generated by Django 3.1.7 on 2021-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_journal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='отображать в популярном?'),
        ),
    ]
