# Generated by Django 3.1.7 on 2021-03-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_journal_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='position_popular',
            field=models.IntegerField(default=1, verbose_name='позиция в популярном'),
        ),
    ]
