# Generated by Django 3.1.7 on 2021-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_journal_position_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='show_in_books',
            field=models.BooleanField(default=False, verbose_name='Показывать в блоке "Книги"'),
        ),
    ]
