# Generated by Django 3.1.7 on 2021-05-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_journal_show_in_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_issue_id',
            field=models.IntegerField(default=0, verbose_name='ID последнего выпуска'),
        ),
    ]
