# Generated by Django 3.1.7 on 2021-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_journal_last_issue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_type',
            field=models.CharField(choices=[('magazine', 'Журнал'), ('paper', 'Газета'), ('book', 'Книга')], db_index=True, default='magazine', max_length=10, verbose_name='тип издания (журнал, газета или книга)'),
        ),
    ]
