# Generated by Django 3.1.7 on 2021-05-18 09:37

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('journal', '0013_journal_journal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название для URL')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер дома')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер,квартиры')),
                ('address_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий по адресу')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, verbose_name='отображать ли на сайте?')),
                ('name', models.CharField(max_length=100, verbose_name='Название издательства')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт издательства')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='publishing_logo/%Y/%m/%d/', verbose_name='Логотип издательства')),
                ('nds', models.SmallIntegerField(default=0, verbose_name='НДС')),
                ('uuid_key', models.CharField(default='', max_length=64, verbose_name='UUID key')),
                ('show_site_link', models.BooleanField(default=False, verbose_name='Отображать ссылку на сайт?')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'издательство',
                'verbose_name_plural': 'издательства',
                'ordering': ('name',),
            },
        ),
    ]
