# Generated by Django 3.1.7 on 2021-05-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_journal_publishing_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishingoffice',
            name='is_public',
        ),
        migrations.AddField(
            model_name='issue',
            name='name_slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название для URL'),
        ),
    ]
