# Generated by Django 3.1.7 on 2021-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_auto_20210518_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_export_to_air',
            field=models.BooleanField(default=False, verbose_name='выгружать ли в авиатранспорт?'),
        ),
    ]
