# Generated by Django 3.2.4 on 2022-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_journal_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_pdf_available',
            field=models.BooleanField(default=False, verbose_name='доступен ли PDF для загрузки?'),
        ),
    ]
