# Generated by Django 3.2.4 on 2022-02-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_journal_is_pdf_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='raw_issue', verbose_name='исходный файл'),
        ),
    ]
