# Generated by Django 3.2.4 on 2022-06-05 12:05

from django.db import migrations, models
import django.db.models.deletion
import main.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_partnercompany'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheremet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='код')),
                ('expire', models.DateTimeField(blank=True, null=True, verbose_name='дата окончания действия')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный?')),
            ],
            options={
                'verbose_name': 'промопрограмма Шереметьево',
                'verbose_name_plural': 'промопрограммы Шереметьево',
            },
        ),
        migrations.CreateModel(
            name='PromoProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='название промопрограммы')),
                ('expire', models.DateTimeField(blank=True, null=True, verbose_name='дата окончания действия промопрограммы')),
                ('max_promocodes', models.IntegerField(default=-1, verbose_name='максимальное количество промокодов по программе')),
                ('is_abonement', models.BooleanField(default=False, verbose_name='Промопрограмма для абонемента?')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Скидка при покупке?')),
                ('months_abonement', models.IntegerField(default=0, verbose_name='Количество месяцев по абонементу')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='стоимость генерации промокода')),
                ('amount_buy', main.models.fields.AmountField(decimal_places=2, default=0, max_digits=12, verbose_name='стоимость промокода для отчетов')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.partnercompany', verbose_name='владелец промопрограммы')),
            ],
            options={
                'verbose_name': 'промопрограмма',
                'verbose_name_plural': 'промопрограммы',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='код')),
                ('expire', models.DateTimeField(blank=True, null=True, verbose_name='дата окончания действия')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_code.promoprogram', verbose_name='промопрограмма')),
                ('used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='пользователь, использовавший код')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
            },
        ),
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('object_id', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='код')),
                ('expire', models.DateTimeField(blank=True, null=True, verbose_name='дата окончания действия')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_giftcode_set', to='accounts.customer', verbose_name='владелец подарочного кода')),
                ('used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='пользователь, использовавший код')),
            ],
            options={
                'verbose_name': 'подарочный код',
                'verbose_name_plural': 'подарочные коды',
            },
        ),
        migrations.CreateModel(
            name='AvailableByPromoProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_code.promoprogram', verbose_name='промопрограмма')),
            ],
            options={
                'verbose_name': 'доступно по промопрограмме',
                'verbose_name_plural': 'доступно по промопрограмме',
            },
        ),
    ]
