# Generated by Django 3.1.7 on 2021-03-02 10:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='счёт пользователя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/%Y/%m/%d/', verbose_name='фотография пользователя')),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Женский'), (1, 'Мужской')], null=True, verbose_name='пол')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
