# Generated by Django 3.1.7 on 2021-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='env',
            name='port',
            field=models.IntegerField(default=8080, unique=True),
        ),
    ]
