# Generated by Django 3.1.7 on 2021-03-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210327_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env',
            name='port',
            field=models.IntegerField(default=8080),
        ),
    ]
