# Generated by Django 3.1.7 on 2021-04-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='maket')),
            ],
        ),
        migrations.AlterField(
            model_name='env',
            name='email',
            field=models.CharField(max_length=60, unique=True, verbose_name='Логин'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='file')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Задача')),
            ],
        ),
    ]
