# Generated by Django 3.1.7 on 2021-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210402_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
