# Generated by Django 3.1.7 on 2021-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task2user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task2user',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
