# Generated by Django 3.1.7 on 2021-04-03 11:04

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='maket',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='maket',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to='files'),
        ),
    ]
