# Generated by Django 3.2.4 on 2022-02-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес электронной почты')),
                ('question', models.TextField(verbose_name='вопрос (обращение) пользователя')),
                ('answer', models.TextField(blank=True, default='', null=True, verbose_name='ответ на обращение пользователя')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
    ]
