# Generated by Django 3.1.7 on 2021-03-26 13:37

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0010_journal_position_popular'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(verbose_name='дата создания')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'подписку',
                'verbose_name_plural': 'Подписки на рассылку',
            },
        ),
        migrations.CreateModel(
            name='Toplog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(verbose_name='дата создания')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во подписчиков')),
                ('count_track', models.IntegerField(default=0, verbose_name='Кол-во приходов')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'История рассылки',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название для URL')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('create', models.DateField(verbose_name='дата создания')),
                ('name', models.CharField(max_length=150, verbose_name='заголовок')),
                ('publication', models.CharField(default=False, max_length=150, verbose_name='Название журнала')),
                ('short_text', models.TextField(blank=True, null=True, verbose_name='короткое описание')),
                ('text', models.TextField(verbose_name='начало статьи')),
                ('text_continue', models.TextField(blank=True, null=True, verbose_name='продолжение')),
                ('image', models.ImageField(upload_to='news/cover/%Y/%m/%d/', verbose_name='изображение ландшафт')),
                ('image_portret', models.ImageField(upload_to='news/cover/%Y/%m/%d/', verbose_name='изображение портрет')),
                ('url', models.URLField(verbose_name='ссылка на ридер')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '480x270', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('cropping_portret', image_cropping.fields.ImageRatioField('image_portret', '205x282', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping portret')),
                ('cropping_square', image_cropping.fields.ImageRatioField('image_portret', '80x80', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping square')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Опубликован?')),
                ('author', models.CharField(blank=True, max_length=250, null=True, verbose_name='Автор')),
                ('sorting', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('issue', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.issue', verbose_name='печатное издание')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'обзор',
                'verbose_name_plural': 'Обзор прессы',
            },
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст анонса')),
                ('cover', models.ImageField(upload_to='featured/cover/%Y/%m/%d/', verbose_name='обложка')),
                ('create', models.DateTimeField(verbose_name='дата создания')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.issuepage', verbose_name='страница печатного издания')),
            ],
            options={
                'verbose_name': 'избранная статья',
                'verbose_name_plural': 'избранные статьи',
            },
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст анонса выпуска')),
                ('create', models.DateTimeField(verbose_name='дата создания')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.issue', verbose_name='выпуск издания')),
            ],
            options={
                'verbose_name': 'анонс выпуска',
                'verbose_name_plural': 'анонсы выпусков',
            },
        ),
    ]
