# Generated by Django 3.1.7 on 2021-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
