# Generated by Django 3.2.7 on 2021-11-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0002_auto_20210326_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='audio_converted',
            field=models.BooleanField(default=False, verbose_name='аудио?'),
        ),
        migrations.AddField(
            model_name='news',
            name='audio_converted',
            field=models.BooleanField(default=False, verbose_name='аудио?'),
        ),
    ]
