# Generated by Django 3.2.7 on 2021-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='article',
            field=models.IntegerField(blank=True, null=True, verbose_name='статья'),
        ),
    ]
