# Generated by Django 3.1.7 on 2021-03-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('article', '0002_auto_20210302_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCoverSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_x', models.SmallIntegerField(default=0, verbose_name='Заголовок x')),
                ('title_y', models.SmallIntegerField(default=0, verbose_name='Заголовок y')),
                ('number_x', models.SmallIntegerField(default=0, verbose_name='Выпуск x')),
                ('number_y', models.SmallIntegerField(default=0, verbose_name='Выпуск y')),
                ('category_x', models.SmallIntegerField(default=0, verbose_name='Категория x')),
                ('category_y', models.SmallIntegerField(default=0, verbose_name='Категория y')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal', verbose_name='издание')),
            ],
        ),
    ]
