# Generated by Django 3.1.7 on 2021-03-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlecoversetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='article_cover/%Y/%m/%d/', verbose_name='обложка cтатьи'),
        ),
    ]
