# Generated by Django 3.1.7 on 2021-03-02 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='номер выпуска')),
                ('release_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='дата выхода выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='наименование издания')),
                ('default_cover', models.ImageField(blank=True, null=True, upload_to='default_journal_cover/%Y/%m/%d/', verbose_name='обложка по умолчанию')),
                ('category', models.ManyToManyField(to='catalog.Category', verbose_name='Категории в Pressa.ru')),
            ],
        ),
        migrations.CreateModel(
            name='IssuePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(verbose_name='номер страницы')),
                ('file_low', models.ImageField(blank=True, null=True, upload_to='low', verbose_name='файл изображения предпросмотра')),
                ('file_middle', models.ImageField(upload_to='medium', verbose_name='файл страницы')),
                ('file_high', models.ImageField(blank=True, null=True, upload_to='high', verbose_name='файл страницы увеличенный')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_set', to='journal.issue', verbose_name='печатное издание')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal', verbose_name='издание'),
        ),
    ]
