# Generated by Django 3.1.7 on 2021-03-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFontSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя шрифта')),
                ('file', models.FileField(upload_to='fonts', verbose_name='Файл')),
            ],
        ),
    ]
