# Generated by Django 3.1.7 on 2021-03-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlefontsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecoversetting',
            name='category_size',
            field=models.SmallIntegerField(default=80, verbose_name='Размер категории'),
        ),
        migrations.AddField(
            model_name='articlecoversetting',
            name='font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.articlefontsetting', verbose_name='шрифт'),
        ),
        migrations.AddField(
            model_name='articlecoversetting',
            name='number_size',
            field=models.SmallIntegerField(default=80, verbose_name='Размер номера'),
        ),
        migrations.AddField(
            model_name='articlecoversetting',
            name='title_size',
            field=models.SmallIntegerField(default=80, verbose_name='Размер заголовка'),
        ),
    ]
