# Generated by Django 3.1.7 on 2021-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210317_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecoversetting',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='article_template_cover/%Y/%m/%d/', verbose_name='обложка'),
        ),
    ]
