# Generated by Django 3.1.7 on 2021-03-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articlecoversetting_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecoversetting',
            name='category_color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный')], default='black', max_length=20, verbose_name='Цвет категории'),
        ),
        migrations.AddField(
            model_name='articlecoversetting',
            name='number_color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный')], default='black', max_length=20, verbose_name='Цвет номера'),
        ),
        migrations.AddField(
            model_name='articlecoversetting',
            name='title_color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный')], default='black', max_length=20, verbose_name='Цвет заголовка'),
        ),
    ]
