# Generated by Django 3.2.7 on 2021-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_taggit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_converted',
            field=models.BooleanField(default=False, verbose_name='аудио?'),
        ),
    ]
