# Generated by Django 3.1.7 on 2021-04-02 13:38

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='счёт пользователя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/%Y/%m/%d/', verbose_name='фотография пользователя')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('telegram', models.CharField(blank=True, max_length=25, null=True, verbose_name='логин в телеграм')),
                ('card', models.CharField(blank=True, max_length=35, null=True, verbose_name='номер карты для приема платежей')),
                ('desc', models.TextField(blank=True, max_length=25, null=True, verbose_name='Стек технологий которыми владеете')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
