# Generated by Django 3.2.7 on 2022-01-26 16:11

from django.db import migrations, models
import django.db.models.deletion
import main.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_mailtemplate_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_num', models.BigIntegerField(default=0, verbose_name='идентификатор заказа')),
                ('operation_amount', main.models.fields.AmountField(decimal_places=2, max_digits=12, verbose_name='сумма операции')),
                ('description', main.models.fields.TruncatingCharField(blank=True, max_length=100, null=True, verbose_name='описание товара')),
                ('operation_status', models.IntegerField(choices=[(0, 'Создан'), (1, 'Успешно оплачен'), (2, 'Ошибка оплаты')], default=0, verbose_name='статус операции')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата операции')),
                ('datetime_last_update', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('transaction_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID транзакции платежной системы')),
                ('provider', main.models.fields.TruncatingCharField(blank=True, max_length=20, null=True, verbose_name='платежный инструмент')),
                ('card_holder', main.models.fields.TruncatingCharField(blank=True, max_length=100, null=True, verbose_name='имя держателя карты')),
                ('card_number', main.models.fields.TruncatingCharField(blank=True, max_length=20, null=True, verbose_name='маскированный номер карты')),
                ('country', main.models.fields.TruncatingCharField(blank=True, max_length=2, null=True, verbose_name='код страны')),
                ('city', main.models.fields.TruncatingCharField(blank=True, max_length=100, null=True, verbose_name='город')),
                ('address', main.models.fields.TruncatingCharField(blank=True, max_length=100, null=True, verbose_name='адрес')),
                ('ip_address', main.models.fields.TruncatingCharField(blank=True, max_length=40, null=True, verbose_name='IP-адрес')),
                ('pd', main.models.fields.TruncatingCharField(blank=True, max_length=250, null=True, verbose_name='pd')),
                ('debug', models.TextField(blank=True, null=True, verbose_name='debug')),
                ('anchor', main.models.fields.TruncatingCharField(blank=True, max_length=250, null=True, verbose_name='anchor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payonline_payment_owner', to='accounts.customer', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
                'ordering': ('payment_num',),
            },
        ),
    ]
